# Generated by Django 3.2.5 on 2021-07-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210721_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('sale', 'Sale'), ('feature', 'Feature')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=50),
        ),
        migrations.AlterField(
            model_name='children',
            name='type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=50),
        ),
        migrations.AddField(
            model_name='gallery',
            name='color',
            field=models.ManyToManyField(to='api.Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='api.Color'),
        ),
    ]
