# Generated by Django 3.2.5 on 2021-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210730_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
