# Generated by Django 3.2.5 on 2021-07-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210730_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
    ]
