# Generated by Django 3.2.5 on 2021-07-31 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 18, 2, 11, 742729, tzinfo=utc)),
        ),
    ]
