# Generated by Django 3.2.5 on 2021-08-03 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120)),
                ('productName', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('price', models.CharField(max_length=30)),
                ('image', models.TextField()),
                ('deliverycharge', models.CharField(default='0', max_length=10)),
                ('status', models.CharField(choices=[('received', 'Received'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('delivered', 'Delivered')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 5, 54, 6, 926000, tzinfo=utc)),
        ),
    ]
