# Generated by Django 3.2.5 on 2021-08-03 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210803_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 12, 54, 29, 77208, tzinfo=utc)),
        ),
    ]
