# Generated by Django 3.2.5 on 2021-08-04 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210803_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 2, 59, 36, 450353, tzinfo=utc)),
        ),
    ]
