# Generated by Django 3.2.5 on 2021-08-04 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('delivered', 'Delivered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 6, 56, 39, 94841, tzinfo=utc)),
        ),
    ]
