# Generated by Django 3.2.5 on 2021-08-05 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210805_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 7, 6, 49, 629796, tzinfo=utc)),
        ),
    ]
